import java.util.*;

class Exception

{

 public static void main(String [] args)

 {

 Scanner sc=new Scanner(System.in);

 System.out.println("Enter two values");

 int num1 = sc.nextInt();

 int num2 =sc.nextInt();

 try{

 System.out.println(num1/num2);

 

 }

 catch(ArithmeticException e){

 

 System.out.println("Num2 cannot be zero");

 }

 

 String str=null;

 

 

 try{

 

 System.out.println(str.length());

 }

 catch(NullPointerException e){

 

 System.out.println("String should not be null");

 

 }

 int a[]={10,20,30};

 try{

 System.out.println(a[3]);

 }

 catch(ArrayIndexOutOfBoundsException e){

 System.out.println("Index is out of bound");

 

 }

}

}

